# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: From Data to Decisions-> A Machine Learning Journey
description: Welcome to ML Insights, a blog dedicated to exploring the fascinating world of machine learning. Join me on this journey as we dive into the latest advancements, practical applications, and insightful case studies in the field of AI and data science. With a focus on demystifying complex concepts, I'll share tutorials, articles, and research findings that empower both beginners and seasoned practitioners. Get ready to unlock the potential of machine learning algorithms, gain practical tips, and discover real-world applications. Let's learn and grow together! 
github_username: fakhar-iqbal

# Email and twitter are optional:
email: fakhareiqbal3534@gmail.com


# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
